#!/usr/bin/env ruby

require_relative 'spec/spec_helper'

# Create models that match your scenario
class TrustedCommunitySolutionEvaluation
  attr_accessor :id, :evaluator

  def initialize(id, evaluator)
    @id = id
    @evaluator = evaluator
  end
  
  def evaluator_id
    evaluator&.id
  end
end

class CommunitySolution
  attr_accessor :id, :user, :trusted_evaluations

  def initialize(id, user)
    @id = id
    @user = user
    @trusted_evaluations = []
  end
  
  # These methods would normally be generated by Rails associations
  # but we need to define them manually for the test
  def trusted_evaluation_ids
    trusted_evaluations.map(&:id)
  end
  
  # This would normally be generated by Rails: has_many :trusted_evaluations
end

class Evaluator
  attr_accessor :id, :name

  def initialize(id, name)
    @id = id
    @name = name
  end
end

# Create serializers that match your scenario
class EvaluatorSerializer
  include JSONAPI::Serializer
  
  set_type :evaluator
  attributes :name
end

class TrustedEvaluationSerializer
  include JSONAPI::Serializer
  
  set_type :'trusted-evaluation'
  belongs_to :evaluator, serializer: EvaluatorSerializer, lazy_load_data: true
end

class CommunitySolutionSerializer
  include JSONAPI::Serializer
  
  set_type :'community-solution'
  has_many :trusted_evaluations, 
           serializer: TrustedEvaluationSerializer, 
           lazy_load_data: true
end

# Create test data
evaluator = Evaluator.new('eval-123', 'John Evaluator')
user = User.fake
solution = CommunitySolution.new('solution-456', user)

trusted_eval = TrustedCommunitySolutionEvaluation.new('te-789', evaluator)
solution.trusted_evaluations = [trusted_eval]

puts "=== Testing trusted-evaluations with lazy_load_data ==="

# Test with includes (should include data)
serialized = CommunitySolutionSerializer.new(
  solution, 
  include: ['trusted_evaluations', 'trusted_evaluations.evaluator']
).serializable_hash

puts "\n=== WITH INCLUDES ==="
puts JSON.pretty_generate(serialized)

# Check if trusted_evaluations are included
has_te_data = serialized.dig(:data, :relationships, :trusted_evaluations, :data)
puts "\nTrusted evaluations data present: #{!has_te_data.nil? && !has_te_data.empty?}"

if serialized[:included]
  te_included = serialized[:included].find { |inc| inc[:type] == :'trusted-evaluation' }
  puts "Trusted evaluation in included: #{!te_included.nil?}"
  
  if te_included
    evaluator_data = te_included.dig(:relationships, :evaluator, :data)
    puts "Evaluator data in trusted evaluation: #{!evaluator_data.nil?}"
    
    evaluator_included = serialized[:included].find { |inc| inc[:type] == :evaluator }
    puts "Evaluator in included: #{!evaluator_included.nil?}"
  end
end

puts "\n" + "="*50

# Test without includes (should not include data)
serialized_no_include = CommunitySolutionSerializer.new(solution).serializable_hash

puts "\n=== WITHOUT INCLUDES ==="
puts JSON.pretty_generate(serialized_no_include)

has_te_data_no_include = serialized_no_include.dig(:data, :relationships, :trusted_evaluations, :data)
puts "\nTrusted evaluations data present: #{!has_te_data_no_include.nil?}"